### ISSUE TITLE
Can't connect to Cloud

### ISSUE THREAD

**Issue by halext** [delid4ve/SonoffJars#2]
It is saying 
COMMUNICATION_ERROR 
Cloud Offline

in the logs it says
[org.apache.felix.fileinstall        ] - Error while starting bundle: file:/usr/share/openhab/addons/org.openhab.binding.sonoff-3.1.0-SNAPSHOT_2.5r6.jar
org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.sonoff [29]
  Unresolved requirement: Import-Package: org.openhab.core
	at org.eclipse.osgi.container.Module.start(Module.java:463) ~[org.eclipse.osgi-3.16.200.jar:?]
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:440) ~[org.eclipse.osgi-3.16.200.jar:?]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1260) [bundleFile:3.6.8]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1233) [bundleFile:3.6.8]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:520) [bundleFile:3.6.8]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365) [bundleFile:3.6.8]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316) [bundleFile:3.6.8]
[ERROR] [unication.SonoffCommunicationManager] - The device xxxx doesnt exist, unable to set state

What can i do ?

**Comment by delid4ve** [comment]
what openhab version?

**Comment by halext** [comment]
Hi,

I have 3.1.
Have instaled another raspPI and a clean openhab. It is working now, i don't know the reason that was giving this errors.
